[project]
name = "poly-storage-engine-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "fastapi>=0.121.1",
    "filetype>=1.2.0",
    "opencv-python>=4.12.0.88",
    "pillow>=12.0.0",
    "pymongo>=4.15.3",
    "python-multipart>=0.0.20",
    "torch>=2.9.0",
    "torchaudio>=2.9.0",
    "torchvision>=0.24.0",
    "transformers>=4.57.1",
    "uvicorn>=0.38.0",
]
